# Generated by Django 5.1 on 2024-08-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_advocate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='profile_picture',
            field=models.CharField(default='https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/corporate-user-icon.png', max_length=500),
        ),
        migrations.AddField(
            model_name='advocate',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='bio',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='username',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
